name: env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.3=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.1.0=h15599e2_0
  - icu=75.1=he02047a_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.24.3=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libcap=2.76=h0b2e76d_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.1=hca5e8e5_0
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - mad=0.15.1b=h9c3ff4c_1
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h2d0b736_3
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openssl=3.5.4=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.24=h68140b3_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shaderc=2025.4=h3e344bc_0
  - snappy=1.2.2=h03e3b7b_0
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.2.0=hb60516a_1
  - tk=8.6.13=noxft_hd72426e_102
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - asteroid==0.4.4
      - asteroid-filterbanks==0.4.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - cached-property==2.0.1
      - cachetools==5.5.2
      - catalyst==21.5
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.1.4
      - debugpy==1.8.17
      - decorator==5.2.1
      - dtw-python==1.1.6
      - easydict==1.13
      - editdistance==0.8.1
      - einops==0.8.1
      - executing==2.2.1
      - fairseq==1.0.0a0+f2146bd
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gdown==5.2.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.1.10
      - huggingface-hub==0.36.0.dev0
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - julius==0.2.7
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kaldi-io==0.9.8
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning-utilities==0.11.9
      - llvmlite==0.39.1
      - lxml==6.0.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mir-eval==0.8.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nltk==3.9.1
      - normalise==0.1.8
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.1.1
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pb-bss-eval==0.0.2
      - pesq==0.0.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - portalocker==3.0.0
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pysndfx==0.3.6
      - pysocks==1.7.1
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytorch-ranger==0.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - roman==4.2
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.7
      - sox==1.5.0
      - soxr==0.3.7
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.4.1
      - torch-optimizer==0.3.0
      - torch-stoi==0.2.3
      - torchaudio==2.4.1
      - torchmetrics==1.5.2
      - torchvision==0.19.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/user/.conda/envs/env
